### ISSUE TITLE
feat: add loading spinner in dashboard

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/dashboard#27]
Currently, there is no loading spinner , so while verifying credentials or during loading the website, either it shows login page or blank page

**Update required**
Show a loading screen with logo[svg recommended] and spinner maintaining same them

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by tanmoysrt** [comment]
> Sounds good to me. I'm willing to contribute. Please assign it to me.

Sure ! Go ahead :+1:

**Comment by tanmoysrt** [comment]
Hi @ChavvaNarayana any update ?
