### ISSUE TITLE
chore: update colors of progress bar in `deploy application` page

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/dashboard#37]
### Is your feature request related to a problem? Please describe

Currently, the progress bar colour of the `deploy application` page, is out of the context of the main application. 

### Describe the solution you'd like

1. The main dashboard is based on a pink colour-based theme. Find out the primary colour palette here - https://github.com/swiftwave-org/swiftwave-dashboard/blob/master/src/theme.js
2. Modify the progress bar to have the same color theme

### Additional context
 
![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/57363826/a94e703d-9391-4921-b4e9-af18e1ac82fe)

### Are you working on this?

No

**Comment by doppedheart** [comment]
can i work on this issue ?

**Comment by tanmoysrt** [comment]
> can i work on this issue ?

sure you can work on the issue

**Comment by tanmoysrt** [comment]
@doppedheart  Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.

**Comment by tanmoysrt** [comment]
Hi @doppedheart any updates ?

**Comment by ShubhaamTiwary** [comment]
Hi, @tanmoysrt , Can I work on this issue??

**Comment by tanmoysrt** [comment]
> Hi, @tanmoysrt , Can I work on this issue??

We are actually moving from old dashboard to completely a new one. So this issue is invalid now.
Sorry, I have forget to close this old one.
