### ISSUE TITLE
feature: add welcome bot

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/dashboard#39]
### Describe the solution you'd like
Adding a `welcome bot` is to provide the required information to first-time contributors to Swiftwave. You need to integrate a welcome bot, which will
- On opening the first issue, send a comment welcoming to SwiftWave community and a link to join slack (https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)
- On opening the first PR, congratulate him for his first contribution, and say to join slack and take a review from the other contributors.

### Additional context
You can check this repo to integrate the welcome bot from wow-actions -> https://github.com/wow-actions/welcome .
We are open to suggestions if you would like to use another bot for welcoming purposes.

**Comment by AdiDecodes** [comment]
@tanmoysrt I would like to work on this, Please assign it to me.

**Comment by tanmoysrt** [comment]
> @tanmoysrt I would like to work on this, Please assign it to me.

Sure go ahead :+1:

**Comment by AdiDecodes** [comment]
> > @tanmoysrt I would like to work on this, Please assign it to me.
> 
> Sure go ahead 👍

Thankyou, waiting till hacktoberfest starts!

**Comment by tanmoysrt** [comment]
@AdiDecodes   Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.

**Comment by tanmoysrt** [comment]
Hi @AdiDecodes any update?

**Comment by AdiDecodes** [comment]
> Hi @AdiDecodes any update?

Working on it.

**Comment by AdiDecodes** [comment]
Hey @tanmoysrt I've created the pull request. Please Verify once.
